### ISSUE TITLE
Idee zur Optimierung von "FLOW"

### ISSUE THREAD

**Issue by hbast** [Fragmon/calibration#2]
Hallo,
ich hätte einen Vorschlag zur Optimierung von "FLOW":
Wenn man die Prozedur startet, heizt der Drucker erst mal das Bett auf die eingegebene Temperatur. Danach wird gehomed und dann erst die Nozzle auf Temperatur gebracht. Wäre es nicht möglich die Nozzle mit dem Bett zusammen auf Temperatur zu bringen? Das würde initial etwas Zeit sparen, da das Bett (beim Vyper) eh recht lange braucht um aufzuheizen.

Alternativ könnte man die Nozzle auf 140°C bringen und im Anschluss an die Homing-Prozedur auf die volle Temperatur bringen.

**Comment by Fragmon** [comment]
Hatte ich mir überlegt, aber um unnötiges oozing zu reduzieren wollte ich das Hotend erst vor dem Start aufheizen.
