### ISSUE TITLE
Fehler in PRESSURE_ADVANCE_CALIBRATION

### ISSUE THREAD

**Issue by Choque** [Fragmon/calibration#5]
Nach einbinden der cfg bekomme ich folgende Fehlermeldung:

`Error loading template 'gcode_macro PRESSURE_ADVANCE_CALIBRATION:gcode': jinja2.exceptions.TemplateSyntaxError: unexpected '}', expected ')'`

Konnte den Fehler beim durchschauen des Codes leider nicht auf Anhieb identifizieren.

**Comment by Fragmon** [comment]
Danke dir. Sollte jetzt wieder gehen. Warten fehlende ) inmm Set Bereich
