### ISSUE TITLE
Unclear which PA lines to expect

### ISSUE THREAD

**Issue by Staubgeborener** [Fragmon/calibration#9]
I need help to find out the correct PA value. Do I go by the best lines between the two bars (left and right) or do I also consider the line quality outside the bars? Depending on this I have a hard time to decide between line 3, 4 or 5 and depending on the decision I get completely different PA values (between 0.1 - 0.2).

![PA1](https://user-images.githubusercontent.com/28908603/227346288-1283ae14-1636-42db-86a5-d44486bdee93.jpg)

**Comment by Fragmon** [comment]
I think you should do another test and decrease the increment and set one around the value of line three.

**Comment by Staubgeborener** [comment]
![PA2](https://user-images.githubusercontent.com/28908603/227362918-8e604a79-f617-403b-ba72-fdbde904d42f.png)

**Comment by Fragmon** [comment]
Try to increase the outer speed. Maybe the Difference between inner and outer is to high for your extruder.

**Comment by Staubgeborener** [comment]
I increased the outer speed from 5 to 140 (160 is the default speed for the middle).

![PA3](https://user-images.githubusercontent.com/28908603/227373872-1fa38291-1575-4f93-b193-b19214fbd757.png)

And this is quite interesting. At first i thought 0.125 or 0.15 is a good PA value. This pictures looks more like way below 0.1.

**Comment by Fragmon** [comment]
No you have a massive Problem. Your First controlline is faulty. Which printer you use?

**Comment by Staubgeborener** [comment]
Ender 3v2. Quite modded over the last years. I am using a briss fang with a microswiss all metal hot end and a direct drive.
